# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "417361600516-terraform-state"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "eu-west-1"
  }
}
