# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  version = "~> 3.0"
  region = "eu-west-1"

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["417361600516"]

  # Make it faster by skipping something
  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = true
  skip_region_validation      = true
  skip_credentials_validation = true
}
