name: 'Pre Commit Check'

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "terraform/**"

jobs:
  pre_commit_check:
    name: Pre Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Pre Commit
        run: |
          brew install pre-commit
          pre-commit --version
          git init
          pre-commit run --all-files
