name: 'Pre Commit Check'

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "terraform/**"

jobs:
  pre_commit_check:
    name: Pre Commit Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 2.7
        run: |
          brew install pyenv
          pyenv install 2.7.16
          pyenv global 2.7.16
      - name: Pre Commit
        run: |
          brew install pre-commit
          pre-commit --version
          pre-commit run --all-files
