name: Terragrunt Apply Refresh-All (Manual workflow)

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      reason:
        # Friendly description to be shown in the UI
        description: 'Why is there a need to refresh the terraform state?'
        # Default value if no value is explicitly provided
        default: 'refresh terraform state'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  apply-refresh-all:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "ubuntu-latest", account: "non-prod", env: "test" }
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform terragrunt
        run: brew install terraform terragrunt
      - name: Terragrunt run-all plan
        run: |
          terragrunt run-all apply -refresh-all \
          --terragrunt-non-interactive \
          --terragrunt-parallelism 1 \
          --terragrunt-working-dir terraform/terragrunt/${{ matrix.config.account }}/${{ matrix.config.env }}
