name: Terragrunt apply

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "terraform/**"

jobs:
  plan:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: [ubuntu-latest, "417361600516"],account: "non-prod",env: "test" }
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform
        run: brew install terraform
      - name: Get terraform Versions
        run: terraform --version
      - name: Install terragrunt
        run: brew install terragrunt
      - name: Get terragrunt Version
        run: terragrunt --version

      - name: Terragrunt run-all plan
        run: |
          terragrunt run-all plan
          --terragrunt-non-interactive
          --terragrunt-parallelism 1
          --terragrunt-working-dir terraform/terragrunt/${{ matrix.config.account }}/${{ matrix.config.env }}

      - name: Terragrunt run-all apply
        run: |
          terragrunt run-all apply
          --terragrunt-non-interactive
          --terragrunt-parallelism 1
          --terragrunt-working-dir terraform/terragrunt/${{ matrix.config.account }}/${{ matrix.config.env }}