name: Terragrunt Plan All (dry run)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      run: |
        brew install tfenv && \
        tfenv install
    - name: Get Terraform Versions
      run: |
        tfenv --version
    - name: Install Terragrunt
      run: |
        brew install tgenv && \
        tgenv install
    - name: Get Terragrunt Versions
      run: |
        tgenv --version
