name: Terragrunt Plan All (dry run)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v2
    - name: Install tfenv
      run: |
        brew install tfenv@1.0.9 && \
        tfenv install
        tfenv us 1.0.9
    - name: Get tfenv Versions
      run: tfenv --version
    - name: Install tgenv
      run: |
        brew install tgenv@0.35.4 && \
        tgenv install
        tgenv use 0.35.4
    - name: Get tgenv Version
      run: tgenv --version
