name: Terragrunt Plan All (dry run)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform and Terragrunt
      run: |
        brew tap rocketinsights/tgenv
        brew install tfenv tgenv
        tfenv install
        tgenv install
    - name: Get Versions
      run: |
        terragrunt --version
        terraform --version
